#version 430
layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 0) uniform image2D pos_samples;
layout(binding = 1) uniform usampler2D pos_mask;
uniform mat4 lightTransform;

void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID);
	uvec4 mask = texelFetch(pos_mask, coords, 0);
	vec4 pos_sample = imageLoad(pos_samples, coords);
	pos_sample.w = 1;

	imageStore(pos_samples, coords, lightTransform * pos_sample * mask.r);
}
